# Generated by Django 5.2.8 on 2025-12-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientprofile_freelancerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
