# Generated by Django 5.2.8 on 2025-12-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_freelancerprofile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('freelancer', 'Freelancer')], default='client', max_length=20),
        ),
    ]
