# Generated by Django 5.2.8 on 2025-12-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_approved_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
