# Generated by Django 5.2.8 on 2025-12-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_clientprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='is_approved',
        ),
    ]
