# Generated by Django 5.2.8 on 2025-12-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_clientprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('freelancer', 'Freelancer')], max_length=20),
        ),
    ]
