# Generated by Django 5.2.8 on 2025-12-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='project_files/'),
        ),
    ]
